/**
 * Audio configuration.
 *
 * Everything here is generated by `node tools/generate-audio.mjs` — there are
 * no samples and no stock audio in this project.
 *
 * Every cue below exists because something specific happens on screen at that
 * frame. Moments with no visual event get no sound: scene 6 is deliberately
 * left to the score, the narration and the breathing ring alone.
 *
 * Reference (30 fps, 1716 frames): scene starts 0 / 166 / 362 / 558 / 874 /
 * 1100 / 1416.
 */
export const AUDIO = {
	music: {
		enabled: true,
		src: "audio/ambient-piano.wav", // ambient piano and pads, no vocals
		peakVolume: 0.5,
		fadeInFrames: 210, // grows across the first 7 seconds
		fadeOutStart: 1500,
		totalFrames: 1716,
	},
	sfx: {
		enabled: true,
		cues: [
			// Scene 1 — sand running through the neck of the hourglass.
			{src: "audio/sand.wav", frame: 14, durationInFrames: 168, volume: 0.1},

			// Scene 2 — the columns climbing, then the question.
			{src: "audio/climb.wav", frame: 176, durationInFrames: 102, volume: 0.13},
			{src: "audio/tension.wav", frame: 282, durationInFrames: 102, volume: 0.2},

			// Scene 3 — the weight of "Não.", then the ring closing around "fase".
			{src: "audio/settle.wav", frame: 380, durationInFrames: 114, volume: 0.2},
			{src: "audio/ring.wav", frame: 530, durationInFrames: 78, volume: 0.14},

			// Scene 4 — one chime for each moon phase the big disc completes.
			{src: "audio/chime-1.wav", frame: 580, durationInFrames: 90, volume: 0.13},
			{src: "audio/chime-2.wav", frame: 631, durationInFrames: 90, volume: 0.13},
			{src: "audio/chime-3.wav", frame: 681, durationInFrames: 90, volume: 0.13},
			{src: "audio/chime-4.wav", frame: 725, durationInFrames: 90, volume: 0.13},
			{src: "audio/chime-5.wav", frame: 775, durationInFrames: 90, volume: 0.13},
			{src: "audio/chime-6.wav", frame: 832, durationInFrames: 90, volume: 0.14},

			// Scene 5 — each sprout opening, and the slow one opening last.
			{src: "audio/bloom.wav", frame: 948, durationInFrames: 72, volume: 0.12},
			{src: "audio/bloom.wav", frame: 1002, durationInFrames: 72, volume: 0.12},
			{src: "audio/bloom.wav", frame: 1032, durationInFrames: 72, volume: 0.12},
			{src: "audio/bloom-big.wav", frame: 1064, durationInFrames: 108, volume: 0.17},

			// Scene 7 — light coming over the horizon, then "Continue." landing.
			{src: "audio/dawn.wav", frame: 1436, durationInFrames: 195, volume: 0.16},
			{src: "audio/settle.wav", frame: 1624, durationInFrames: 92, volume: 0.2},
		],
	},
} as const;
