import {SCENE_STARTS_IF} from "../Ifood";

export type SfxCueIF = {src: string; frame: number; durationInFrames: number; volume: number};

/**
 * Audio configuration for "iFood — a virada".
 *
 * Everything here is generated by `node tools/generate-audio.mjs ifood` — no
 * samples, no stock audio anywhere in this project.
 *
 * Brief constraints the `som` agent must hold:
 *  - NO bell / chime, ever.
 *  - NO piano as a lead instrument. The bed is low drone + light electronic
 *    texture + a constant pulse, tension rising gradually, no vocals, no
 *    emotional melody. Always under the voice.
 *  - Few effects, each one locked to a VISUAL EVENT, never to a scene change:
 *    soft impacts on dates, discreet whooshes on motivated transitions, small
 *    UI clicks on interfaces, phone-room ambience in scene 1, a subtle
 *    map/tech texture in scenes 6-7, and the single strongest impact on the
 *    2018 reveal.
 *
 * VOCABULARY (files the generator writes to public/audio/ifood/):
 *
 *   score.wav          the 63s bed — low drone, constant pulse, rising tension
 *   paper-impact.wav   the word "PAPEL" landing (sc1). Low drop + dry
 *                      transient. Cinematic, discreet, never a bell.
 *   date-impact.wav    a year appearing: 2011 / 2012 / 2013. Softer sibling
 *                      of the above. Reusable.
 *   reveal-2018.wav    the 2018 turn (sc7). Pre-swell, deep drop, wide burst,
 *                      long sub tail. THE loudest moment of the film.
 *   whoosh.wav         a pass-by for a motivated transition, L -> R, 1.0s.
 *   whoosh-up.wav      a rising transition, for a cut that climbs, 1.3s.
 *   ui-click-1/2/3.wav 140ms interface taps (sc4). Three variants so a burst
 *                      of them never machine-guns.
 *   phone-room.wav     9.84s (= 295 frames, exactly scenes 1+2): room tone,
 *                      mains hum, two distant landline rings, keypad clicks.
 *   map-texture.wav    9.0s (= 270 frames, exactly scene 6 and scene 7):
 *                      filtered air sweeping, sparse data clicks, faint
 *                      beating high drone.
 *   net-pulse.wav      one node joining the network (sc7). 550ms, electronic.
 *
 * CUE STATUS: only the two scene-length AMBIENCES are placed so far — they
 * are properties of a whole scene, not of an instant, so they need neither
 * the narration nor the final visuals. Every event-locked cue (the impacts,
 * the whooshes, the clicks, the 2018 reveal, the network nodes) is still
 * pending: those must be anchored on `lineIF(id)` / the real visual frames,
 * which do not exist yet. Adding them blind would put sound where nothing
 * happens on screen, which is exactly what the brief forbids.
 *
 * `sfx.cues` is a getter (not a plain array) so this module can read scene
 * starts and narration lines lazily, after every module has initialised — the
 * same cycle-avoidance trick audio-cp.ts relies on.
 */
const IF_SFX = "audio/ifood/";

const computeSfxCuesIF = (): SfxCueIF[] => {
	const cues: SfxCueIF[] = [];

	/* ---- Ambiences: scene-length beds, not events ---- */

	// Scenes 1-2 happen in a room where orders arrive by telephone. The file
	// is cut to exactly the two scenes (295 frames) and fades at both ends.
	cues.push({
		src: `${IF_SFX}phone-room.wav`,
		frame: SCENE_STARTS_IF[0],
		durationInFrames: 295,
		volume: 0.09,
	});

	// Scenes 6-7 live on maps and networks. One 270-frame pass per scene.
	cues.push({
		src: `${IF_SFX}map-texture.wav`,
		frame: SCENE_STARTS_IF[5],
		durationInFrames: 270,
		volume: 0.08,
	});
	cues.push({
		src: `${IF_SFX}map-texture.wav`,
		frame: SCENE_STARTS_IF[6],
		durationInFrames: 270,
		volume: 0.09,
	});

	/* ---- Event cues: added once the narration frames and the scenes'
	   real visual beats are measured. See CUE STATUS above. ---- */

	return cues.sort((a, b) => a.frame - b.frame);
};

export const AUDIO_IF = {
	music: {
		/** Flipped on by the `som` agent once score.wav exists. */
		enabled: false,
		src: `${IF_SFX}score.wav`,
		peakVolume: 0.42,
		fadeInFrames: 30,
		fadeOutStart: 1760,
		totalFrames: 1890,
	},
	sfx: {
		/**
		 * Off with the score: the cues below point at files that only exist
		 * after the generator runs, and a missing src breaks `motion`'s
		 * preview. Flip both flags together, right after the synthesis.
		 */
		enabled: false,
		get cues(): SfxCueIF[] {
			return computeSfxCuesIF();
		},
	},
};
