/**
 * Audio configuration for "Recomeçar" (sufixo rc).
 *
 * Everything here is generated by `node tools/generate-audio.mjs` — there are
 * no samples and no stock audio in this project.
 *
 * Every cue below exists because something specific happens on screen at that
 * frame. Moments with no visual event get no sound.
 *
 * Reference (30 fps, 900 frames): scene starts 0 / 120 / 210 / 420 / 540 / 720 / 900.
 */
export const AUDIO_RC = {
	music: {
		enabled: false, // sem trilha por pedido
		peakVolume: 0,
	},
	sfx: {
		enabled: true,
		cues: [
			// Scene 1 — whoosh sutil no instante da queda.
			{src: "audio/rc/fall-whoosh.wav", frame: 120, durationInFrames: 48, volume: 0.12},

			// Scene 3 — som suave ao terminar de se levantar.
			{src: "audio/rc/breath-land.wav", frame: 480, durationInFrames: 60, volume: 0.15},
		],
	},
} as const;
