import {SCENE_STARTS_CP} from "../ComecePequeno";
import {NARRATION_CP, line} from "./narration-cp";

/**
 * Audio configuration for "Comece Pequeno".
 *
 * Everything here is generated by `node tools/generate-audio.mjs comece-pequeno`
 * — no samples and no stock audio anywhere in this project.
 *
 * Every cue exists because something specific happens on screen at that frame
 * (a card landing, a counter ticking, a client dot joining, a door of numbers
 * opening). Moments with no visual event get no sound.
 *
 * Reference (30 fps, 2164 frames): scene starts 0 / 346 / 662 / 1038 / 1714.
 *
 * Most cues are LOCKED TO THE VOICE: they are computed from `line(id)` in
 * narration-cp.ts, not from hardcoded frame numbers, so re-measuring the
 * narration re-times the sound design for free (see cue-cp.ts for the same
 * pattern used by the scenes themselves). A few cues are purely visual —
 * they never had a voice anchor to begin with — and those are expressed as
 * an offset from the relevant scene's start instead.
 *
 * `sfx.cues` is a getter (not a plain array) so this module can read
 * SCENE_STARTS_CP from ComecePequeno.tsx, which imports the scenes, which
 * import cue-cp.ts, which imports this same constant back — a cycle. Reading
 * it lazily, inside a function only called at render time by SoundtrackCP,
 * means every module has finished initialising by the time it runs (the
 * exact trick cue-cp.ts already relies on).
 */
const CP_SFX = "audio/cp/";

type SfxCue = {src: string; frame: number; durationInFrames: number; volume: number};

const computeSfxCuesCP = (): SfxCue[] => {
	if (!NARRATION_CP.enabled) return [];

	const cues: SfxCue[] = [];

	/* ---- Scene 1 (hook), starts at SCENE_STARTS_CP[0] ---- */

	// The twelve cards: distributed inside "01-em-2013", starting ~46% into
	// the line and the twelfth landing exactly as it ends — mirrors the
	// `dealStart` / `step` math in Scene1Hook.tsx.
	const l1 = line("01-em-2013");
	const dealStart = Math.round(l1.frame + l1.durationInFrames * 0.46);
	const dealEnd = l1.frame + l1.durationInFrames;
	const dealSpan = Math.max(24, dealEnd - dealStart);
	const dealStep = dealSpan / 11;
	for (let i = 0; i < 12; i++) {
		cues.push({
			src: `${CP_SFX}card-${String(i + 1).padStart(2, "0")}.wav`,
			frame: Math.round(dealStart + i * dealStep),
			durationInFrames: i === 11 ? 22 : 18,
			volume: i === 11 ? 0.18 : 0.13,
		});
	}

	// The grid receding to almost nothing — purely visual, scene-relative.
	cues.push({
		src: `${CP_SFX}grid-min.wav`,
		frame: SCENE_STARTS_CP[0] + 309,
		durationInFrames: 30,
		volume: 0.12,
	});

	/* ---- Scene 2 (risk), starts at SCENE_STARTS_CP[1] ---- */

	// The seven towers, escalated 14 frames apart from where the market line
	// starts — mirrors the `riseStep` stagger in Scene2Risk.tsx closely
	// enough for sound design (the visual stagger is finer-grained).
	const l3 = line("03-mercado");
	for (let i = 0; i < 7; i++) {
		cues.push({
			src: `${CP_SFX}tower-${i + 1}.wav`,
			frame: l3.frame + i * 14,
			durationInFrames: 66,
			volume: 0.16,
		});
	}

	// The small thing entering with its halo — purely visual, scene-relative.
	cues.push({
		src: `${CP_SFX}small-halo.wav`,
		frame: SCENE_STARTS_CP[1] + 137,
		durationInFrames: 96,
		volume: 0.16,
	});

	// The doubt: light dips hardest around 55% into "04-nao-daria-certo",
	// and comes back by the time the line ends — mirrors the `doubt` curve.
	const l4 = line("04-nao-daria-certo");
	cues.push({
		src: `${CP_SFX}tremor.wav`,
		frame: Math.round(l4.frame + l4.durationInFrames * 0.55),
		durationInFrames: 72,
		volume: 0.14,
	});
	cues.push({
		src: `${CP_SFX}light-return.wav`,
		frame: l4.frame + l4.durationInFrames,
		durationInFrames: 84,
		volume: 0.16,
	});

	/* ---- Scene 3 (turn), starts at SCENE_STARTS_CP[2] ---- */

	// The three clients, each on the line that names them.
	const clientLines = ["06-um-cliente", "07-depois-outro", "08-e-outro"];
	for (const id of clientLines) {
		cues.push({
			src: `${CP_SFX}client-impact.wav`,
			frame: line(id).frame,
			durationInFrames: 72,
			volume: 0.18,
		});
	}

	// The burst as the crowd starts and the camera pulls back.
	const l9 = line("09-comecar-crescer");
	cues.push({
		src: `${CP_SFX}burst.wav`,
		frame: l9.frame,
		durationInFrames: 48,
		volume: 0.2,
	});

	// The city rising — purely visual, scene-relative.
	cues.push({
		src: `${CP_SFX}city-rise.wav`,
		frame: SCENE_STARTS_CP[2] + 338,
		durationInFrames: 90,
		volume: 0.16,
	});

	/* ---- Scene 4 (lesson), starts at SCENE_STARTS_CP[3] ---- */

	// The five items, one per spoken line.
	const itemLines = ["12-pode-comecar", "13-guardar", "14-aprender", "15-divida", "16-investir"];
	itemLines.forEach((id, i) => {
		cues.push({
			src: `${CP_SFX}item-${i + 1}.wav`,
			frame: line(id).frame,
			durationInFrames: 54,
			volume: 0.15,
		});
	});

	// The list closing: the five equalise ~52 frames after the last item's
	// line ends.
	const lastItem = line("16-investir");
	cues.push({
		src: `${CP_SFX}list-close.wav`,
		frame: lastItem.frame + lastItem.durationInFrames + 52,
		durationInFrames: 102,
		volume: 0.18,
	});

	/* ---- Scene 5 (final), starts at SCENE_STARTS_CP[4] ---- */

	// The 36 "small repeated decisions" ticking along the baseline, from the
	// line that names them to the top of the curve. Kept deliberately below
	// the usual 0.10-0.22 sfx range — this is texture, not percussion, and
	// the brief calls for it to be "quase subliminar".
	const l17 = line("17-dinheiro-assim");
	const curvePeak = SCENE_STARTS_CP[4] + 358; // "topo da curva" — purely visual
	const TICKS = 36;
	for (let i = 0; i < TICKS; i++) {
		const t = i / (TICKS - 1);
		cues.push({
			src: `${CP_SFX}tick.wav`,
			frame: Math.round(l17.frame + (curvePeak - l17.frame) * t),
			durationInFrames: 6,
			volume: 0.06,
		});
	}

	// The top of the curve.
	cues.push({
		src: `${CP_SFX}peak.wav`,
		frame: curvePeak,
		durationInFrames: 108,
		volume: 0.2,
	});

	// The cut to the black card — purely visual, scene-relative.
	cues.push({
		src: `${CP_SFX}cut-black.wav`,
		frame: SCENE_STARTS_CP[4] + 372,
		durationInFrames: 66,
		volume: 0.14,
	});

	return cues.sort((a, b) => a.frame - b.frame);
};

export const AUDIO_CP = {
	music: {
		enabled: true,
		src: "audio/cp/score.wav",
		peakVolume: 0.5,
		fadeInFrames: 120,
		fadeOutStart: 1980,
		totalFrames: 2164,
	},
	sfx: {
		enabled: true,
		get cues(): SfxCue[] {
			return computeSfxCuesCP();
		},
	},
};
