import {cueForIF} from "./cue-if";
import {NARRATION_IF} from "./narration-if";
import {SCENE_STARTS_IF} from "./timeline-if";

/**
 * Audio configuration for "IFood".
 *
 * Everything here is generated by `node tools/generate-audio.mjs ifood` — no
 * samples and no stock audio anywhere in this project.
 *
 * Every cue exists because something specific happens on screen at that frame.
 * Most of them are LOCKED TO THE VOICE: their frame is computed from the same
 * `cueForIF` / line the scene itself uses, so re-measuring the narration
 * re-times the sound design for free. The few cues with no voice anchor (a page
 * sweep, a shot cut, the map pulling back) are offsets from their scene's start
 * and are marked as such.
 *
 * Reference (30 fps, 1950 frames): scene starts 0 / 239 / 497 / 694 / 848 /
 * 1005 / 1192 / 1458 / 1654, all derived in src/utils/timeline-if.ts.
 *
 * Scene 9 has NO cue at all. The film ends on one point pulsing along one
 * route, and the brief for that scene is silence: adding anything there would
 * be sound for its own sake.
 *
 * `sfx.cues` is a getter rather than a plain array, the same pattern as
 * audio-cp.ts: the cues are computed at render time, after every module has
 * finished initialising, and they always read the current narration numbers.
 */
const IF_SFX = "audio/ifood/";
const S = SCENE_STARTS_IF;

type SfxCue = {src: string; frame: number; durationInFrames: number; volume: number};

const computeSfxCuesIF = (): SfxCue[] => {
	if (!NARRATION_IF.enabled) return [];

	const cues: SfxCue[] = [];

	/* ---- Scene 1 (hook) — SCENE_STARTS_IF[0] ---- */

	// The hand sweeping the page left. Purely visual: Scene1Hook.tsx:50 ramps
	// `turn` over frames 118-152, and the sound lands where the sweep starts.
	cues.push({src: `${IF_SFX}page-turn.wav`, frame: S[0] + 118, durationInFrames: 22, volume: 0.14});

	// PAPEL stamped on the frame. Scene1Hook.tsx:33 — `papel = l.at(0.8)`.
	const c1 = cueForIF(0);
	cues.push({
		src: `${IF_SFX}impact-papel.wav`,
		frame: Math.round(S[0] + c1("01-gancho").at(0.8)),
		durationInFrames: 30,
		volume: 0.22,
	});

	/* ---- Scene 2 (beginning, 2011) — SCENE_STARTS_IF[1] ---- */

	// "2011" and "DISK COOK" landing. Scene2Start.tsx:30-31 — `year` and
	// `brand`, the two fractions of the spoken line.
	const c2 = cueForIF(1);
	const l2 = c2("02-2011");
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[1] + l2.at(0.155)),
		durationInFrames: 14,
		volume: 0.11,
	});
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[1] + l2.at(0.38)),
		durationInFrames: 14,
		volume: 0.11,
	});

	// The telephone. Scene2Start.tsx:92 — the shot cuts in at local 224; the
	// handset leaves the cradle at local 230 (line 38), 0.2s into the file, so
	// we cut into a ring already happening and the lift lands on the animation.
	cues.push({src: `${IF_SFX}phone-ring.wav`, frame: S[1] + 224, durationInFrames: 54, volume: 0.16});

	/* ---- Scene 3 (the shift) — SCENE_STARTS_IF[2] ---- */

	// The same list of dishes jumping paper -> CRT -> phone. Scene3Shift.tsx:
	// shots in at local 54 (line 80), 100 (line 83), then the edit breaking into
	// a sprint at 140 (88), 148 (91) and landing on the phone at 156 (94).
	const c3 = cueForIF(2);
	const l3 = c3("03-mudando");
	for (const [cut, volume] of [
		[54, 0.13],
		[100, 0.13],
		[140, 0.11],
		[148, 0.11],
		[156, 0.15],
	]) {
		cues.push({src: `${IF_SFX}switch.wav`, frame: S[2] + cut, durationInFrames: 14, volume});
	}

	// "DO PAPEL" / "PARA O DIGITAL". Scene3Shift.tsx:30-31 — `offPaper` at 84%
	// of the line, `toDigital` sixteen frames after it.
	const offPaper = Math.round(S[2] + l3.at(0.84));
	cues.push({src: `${IF_SFX}marker.wav`, frame: offPaper, durationInFrames: 14, volume: 0.12});
	cues.push({src: `${IF_SFX}marker.wav`, frame: offPaper + 16, durationInFrames: 14, volume: 0.12});

	/* ---- Scene 4 (site + apps, 2012) — SCENE_STARTS_IF[3] ---- */

	// "2012" and "SITE + APP". Scene4Apps.tsx:30-31.
	const c4 = cueForIF(3);
	const l4 = c4("04-2012");
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[3] + l4.at(0.28)),
		durationInFrames: 14,
		volume: 0.12,
	});
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[3] + l4.at(0.56)),
		durationInFrames: 14,
		volume: 0.12,
	});

	// The restaurant's screen coming on. Scene4Apps.tsx:48 — `crtOn` ramps from
	// local 122.
	cues.push({src: `${IF_SFX}switch.wav`, frame: S[3] + 122, durationInFrames: 14, volume: 0.12});

	// The four orders landing at once. Scene4Apps.tsx:113 — the badges pop at
	// local 128 + 0 / 6 / 12 / 18.
	for (const d of [0, 6, 12, 18]) {
		cues.push({src: `${IF_SFX}notify.wav`, frame: S[3] + 128 + d, durationInFrames: 20, volume: 0.12});
	}

	/* ---- Scene 5 (investment, 2013) — SCENE_STARTS_IF[4] ---- */

	// "2013" and "INVESTIMENTO". Scene5Invest.tsx:30-31.
	const c5 = cueForIF(4);
	const l5 = c5("05-2013");
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[4] + l5.at(0.04)),
		durationInFrames: 14,
		volume: 0.12,
	});
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[4] + l5.at(0.8)),
		durationInFrames: 14,
		volume: 0.12,
	});

	// The line starting to climb. Scene5Invest.tsx:38 — `chart` ramps from
	// local 46.
	cues.push({src: `${IF_SFX}chart.wav`, frame: S[4] + 46, durationInFrames: 34, volume: 0.16});

	/* ---- Scene 6 (the challenge) — SCENE_STARTS_IF[5] ---- */

	// "O DESAFIO". Scene6Challenge.tsx:32.
	const c6 = cueForIF(5);
	const l6 = c6("06-desafio");
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[5] + l6.at(0.22)),
		durationInFrames: 14,
		volume: 0.12,
	});

	// The customer waiting: the clock's hands sweeping. Scene6Challenge.tsx:35 —
	// `tick` runs over local 30-62, five ticks across it. Deliberately below the
	// usual sfx range: this is the texture of the wait, not percussion.
	for (const t of [30, 38, 46, 54, 62]) {
		cues.push({src: `${IF_SFX}tick-clock.wav`, frame: S[5] + t, durationInFrames: 8, volume: 0.09});
	}

	// The route reaching further than it can. Scene6Challenge.tsx:40 — `routeDraw`
	// ramps from local 112. It never lands, because the scene doesn't either.
	cues.push({src: `${IF_SFX}tension-rise.wav`, frame: S[5] + 112, durationInFrames: 70, volume: 0.15});

	// Every order in the city at once. Scene6Challenge.tsx:139 — the five badges
	// pop at local 150 + 0 / 5 / 10 / 15 / 20.
	for (const d of [0, 5, 10, 15, 20]) {
		cues.push({src: `${IF_SFX}notify.wav`, frame: S[5] + 150 + d, durationInFrames: 20, volume: 0.1});
	}

	// "LOGÍSTICA". Scene6Challenge.tsx:33 — `logistics` at 87% of the line.
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[5] + l6.at(0.87)),
		durationInFrames: 14,
		volume: 0.12,
	});

	/* ---- Scene 7 (the turn, 2018) — SCENE_STARTS_IF[6] ---- */

	// "2018". Scene7Turn.tsx:54 — `year` at 16% of the line. The strongest beat
	// of the film, and it gets the strongest effect.
	const c7 = cueForIF(6);
	const l7 = c7("07-2018");
	cues.push({
		src: `${IF_SFX}impact-2018.wav`,
		frame: Math.round(S[6] + l7.at(0.16)),
		durationInFrames: 84,
		volume: 0.22,
	});

	// The chain forming: restaurant, iFood, courier, customer. Scene7Turn.tsx:58
	// — `pinP(delay)` ramps twenty frames from `nodesStart` (42% of the line)
	// plus 0 / 14 / 28 / 42.
	const nodesStart = Math.round(S[6] + l7.at(0.42));
	for (const d of [0, 14, 28, 42]) {
		cues.push({src: `${IF_SFX}pin-drop.wav`, frame: nodesStart + d, durationInFrames: 22, volume: 0.18});
	}

	// The pull-back: the same chain repeating across the whole city.
	// Scene7Turn.tsx:89 and 150 — `pullBack` ramps over local 188-238 and the
	// five echo chains fade in at pullBack = 0 / .08 / .16 / .24 / .32, i.e.
	// every four frames from local 188. Quieter than the four that started it.
	for (let i = 0; i < 5; i++) {
		cues.push({
			src: `${IF_SFX}pin-drop.wav`,
			frame: S[6] + 188 + i * 4,
			durationInFrames: 22,
			volume: 0.13,
		});
	}

	// "LOGÍSTICA". Scene7Turn.tsx:56 — `logistics` at 92% of the line.
	cues.push({
		src: `${IF_SFX}marker.wav`,
		frame: Math.round(S[6] + l7.at(0.92)),
		durationInFrames: 14,
		volume: 0.12,
	});

	/* ---- Scene 8 (transformation) — SCENE_STARTS_IF[7] ---- */

	// The fourteen cuts of the montage. Scene8Transform.tsx:35 — the same `cuts`
	// array, accumulated into shot starts exactly as the scene does it.
	const c8 = cueForIF(7);
	const l8 = c8("08-transformacao");
	const cuts = [16, 15, 15, 14, 14, 13, 13, 12, 12, 12, 12, 13, 15, 18];
	let acc = 0;
	for (const d of cuts) {
		cues.push({src: `${IF_SFX}cut.wav`, frame: S[7] + acc, durationInFrames: 10, volume: 0.1});
		acc += d;
	}

	// PAPEL, APP, PLATAFORMA — the three words landing on the montage.
	// Scene8Transform.tsx:31-33, at 4% / 46% / 79% of the line.
	for (const t of [0.04, 0.46, 0.79]) {
		cues.push({
			src: `${IF_SFX}marker.wav`,
			frame: Math.round(S[7] + l8.at(t)),
			durationInFrames: 14,
			volume: 0.12,
		});
	}

	/* ---- Scene 9 (the close) — deliberately silent ---- */

	return cues.sort((a, b) => a.frame - b.frame);
};

export const AUDIO_IF = {
	music: {
		enabled: true,
		src: "audio/ifood/score.wav",
		peakVolume: 0.45,
		/** The bed comes up under the hook, over 90 frames. */
		fadeInFrames: 90,
		/** Scene 6 — the challenge. From here the bed starts to climb. */
		riseStart: 1005,
		/** Scene 7 — the 2018 impact. The peak the whole film builds to. */
		peakStart: 1233,
		/** Scene 9 — every percussive layer has stopped; the bed resolves. */
		resolveStart: 1654,
		/** Where the bed starts leaving, held under the last words. */
		fadeOutStart: 1830,
		totalFrames: 1950,
	},
	sfx: {
		enabled: true,
		get cues(): SfxCue[] {
			return computeSfxCuesIF();
		},
	},
};
