import {cueForNF} from "./cue-nf";
import {NARRATION_NF} from "./narration-nf";
import {END_NF, SCENE_STARTS_NF} from "./timeline-nf";

/**
 * Audio configuration for "Netflix" (the "Você sabia" documentary).
 *
 * Everything here is generated by `node tools/generate-audio.mjs netflix` —
 * no samples and no stock audio anywhere in this project.
 *
 * Every cue exists because something specific happens on screen at that frame.
 * None of them is a typed-in number: each one is computed from the same
 * `cueForNF` / `atText` the scene itself uses, so re-measuring the narration
 * re-times the whole sound design for free. The file:line in each comment is
 * the event the cue was written for.
 *
 * Reference (30 fps, 2732 frames = END_NF): scene starts 0 / 153 / 443 / 708 /
 * 1003 / 1197 / 1470 / 1710 / 2108 / 2494, all derived in src/utils/timeline-nf.ts
 * from src/narration-netflix.json.
 *
 * `sfx.cues` is a getter rather than a plain array, the same pattern as
 * audio-if.ts: the cues are computed at render time, after every module has
 * finished initialising, and they always read the current narration numbers.
 *
 * Mixing: the voice leads. Every effect sits between 0.11 and 0.20, and the bed
 * (peak 0.5) is multiplied by `musicDuckNF` under each spoken line.
 *
 * `durationInFrames` is always the length of the wav or longer, never shorter:
 * a Sequence that ends mid-file cuts the envelope and leaves a click. The wav
 * lengths are the ones printed by the generator.
 */
const NF_SFX = "audio/netflix/";
const S = SCENE_STARTS_NF;

type SfxCue = {src: string; frame: number; durationInFrames: number; volume: number};

/* Readers for the bed's own curve. They live at module scope because the curve
 * below is read by SoundtrackNF as plain fields; nothing here imports back into
 * this module, so there is no initialisation cycle. */
const c5Curve = cueForNF(4)("05-pergunta");
const c8Curve = cueForNF(7)("08-mundo");
const c10Curve = cueForNF(9)("10-final");

/** The frame the wordmark surfaces in the close (Scene10.tsx:24-26, `markOp`
 *  ramping from `sink + 12`, where `sink = cue.end`). */
const MARK_AT_NF = S[9] + c10Curve.end + 12;

const computeSfxCuesNF = (): SfxCue[] => {
	if (!NARRATION_NF.enabled) return [];

	const cues: SfxCue[] = [];

	/* ---- Scene 1 (hook) — SCENE_STARTS_NF[0] ---- */

	const c1 = cueForNF(0)("01-gancho");

	// NETFLIX lands on the frame. Scene1.tsx:66 — TextNF start={sayNetflix},
	// `sayNetflix = cue.at(0.27)`.
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[0] + c1.at(0.27)),
		durationInFrames: 14,
		volume: 0.13,
	});

	// The DVD sliding in from the right while it turns. Scene1.tsx:39-61 — the
	// disc's `range` opens at `sayDvd - 14` with `rotate={[-50, 40]}`; the sound
	// starts where the disc does. "+ DVDs" (Scene1.tsx:69) lands on the same
	// beat, so it rides this effect instead of getting one of its own.
	cues.push({
		src: `${NF_SFX}whoosh.wav`,
		frame: Math.round(S[0] + c1.at(0.6) - 14),
		durationInFrames: 26,
		volume: 0.12,
	});

	/* ---- Scene 2 (1997 / 1998) — SCENE_STARTS_NF[1] ---- */

	const c2 = cueForNF(1)("02-comeco");

	// "1997". Scene2.tsx:63 — TextNF start={cue.start + 4}.
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[1] + c2.start + 4),
		durationInFrames: 40,
		volume: 0.16,
	});

	// "1998" landing together with the red mailer replacing the 1997 logo.
	// Scene2.tsx:96 — start={say1998}, `say1998 = swap + 4` (Scene2.tsx:23),
	// the same frame the envelope photo's `range` opens (Scene2.tsx:89). One
	// cue for the cut and the year, because they are one beat.
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[1] + c2.at(0.41) + 4),
		durationInFrames: 40,
		volume: 0.16,
	});

	// "DVD" in red over the envelope. Scene2.tsx:99 — TextNF start={sayDvd}.
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[1] + c2.at(0.6)),
		durationInFrames: 14,
		volume: 0.11,
	});

	/* ---- Scene 3 (the problem, then the turn) — SCENE_STARTS_NF[2] ---- */

	const c3 = cueForNF(2)("03-problema");

	// The three complaints. Scene3.tsx:52 / :55 / :60 — MULTAS at cue.at(0.27),
	// DATAS DE DEVOLUÇÃO at cue.at(0.36), POUCA CONVENIÊNCIA at cue.at(0.55).
	for (const [t, volume] of [
		[0.27, 0.12],
		[0.36, 0.12],
		[0.55, 0.12],
	]) {
		cues.push({
			src: `${NF_SFX}marker.wav`,
			frame: Math.round(S[2] + c3.at(t)),
			durationInFrames: 14,
			volume,
		});
	}

	// The red panel sweeping the frame — the accent entering the film.
	// Scene3.tsx:23 — `wipe = cue.atText("Então") - 4`; the panel's translateY
	// runs from `wipe` (Scene3.tsx:26 and :87).
	cues.push({
		src: `${NF_SFX}whoosh.wav`,
		frame: Math.round(S[2] + c3.atText("Então") - 4),
		durationInFrames: 26,
		volume: 0.16,
	});

	// "MUDOU AS REGRAS". Scene3.tsx:81 — TextNF start={cue.at(0.86)}.
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[2] + c3.at(0.86)),
		durationInFrames: 14,
		volume: 0.12,
	});

	/* ---- Scene 4 (subscription, 1 million) — SCENE_STARTS_NF[3] ---- */

	const c4 = cueForNF(3)("04-assinatura");

	// ASSINATURA / SEM DATA DE DEVOLUÇÃO / SEM MULTA, the three promises.
	// Scene4.tsx:40 / :43 / :46 — cue.at(0.23) / (0.37) / (0.52).
	for (const [t, volume] of [
		[0.23, 0.12],
		[0.37, 0.11],
		[0.52, 0.11],
	]) {
		cues.push({
			src: `${NF_SFX}marker.wav`,
			frame: Math.round(S[3] + c4.at(t)),
			durationInFrames: 14,
			volume,
		});
	}

	// "2003" over the wall of DVDs. Scene4.tsx:68 — cue.at(0.68). The photo swap
	// four frames earlier (Scene4.tsx:50-67, `range` from `swap`) is a cross
	// dissolve into this number, so it has no cue of its own.
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[3] + c4.at(0.68)),
		durationInFrames: 40,
		volume: 0.16,
	});

	// "1 MILHÃO" — the first real number of the film. Scene4.tsx:71 —
	// cue.at(0.82). A touch louder than the years, still under the voice.
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[3] + c4.at(0.82)),
		durationInFrames: 40,
		volume: 0.19,
	});

	/* ---- Scene 5 (the question) — SCENE_STARTS_NF[4] ---- */

	const c5 = cueForNF(4)("05-pergunta");

	// "E SE…". Scene5.tsx:146 — TextNF start={cue.start + 6}.
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[4] + c5.start + 6),
		durationInFrames: 14,
		volume: 0.12,
	});

	// "NÃO FOSSE PELO CORREIO?". Scene5.tsx:149 — TextNF start={cue.at(0.47)}.
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[4] + c5.at(0.47)),
		durationInFrames: 14,
		volume: 0.11,
	});

	// The iris opening from the disc's centre onto the computer. Scene5.tsx:81 —
	// `r` ramps from `iris = cue.at(0.6)`, and the clipPath circle that reveals
	// the photo is Scene5.tsx:124. One of the three real transitions of the film.
	cues.push({
		src: `${NF_SFX}whoosh.wav`,
		frame: Math.round(S[4] + c5.at(0.6)),
		durationInFrames: 30,
		volume: 0.15,
	});

	// "INTERNET" landing on the light. Scene5.tsx:155 — TextNF start={sayNet},
	// `sayNet = cue.at(0.88)` (Scene5.tsx:79).
	cues.push({
		src: `${NF_SFX}marker-tech.wav`,
		frame: Math.round(S[4] + c5.at(0.88)),
		durationInFrames: 16,
		volume: 0.14,
	});

	/* ---- Scene 6 (streaming, 2007) — SCENE_STARTS_NF[5] ---- */

	const c6 = cueForNF(5)("06-streaming");

	// "2007" — the turn of the whole film, and the one date that gets more than
	// a thud. Scene6.tsx:42 — TextNF start={cue.start + 6}.
	cues.push({
		src: `${NF_SFX}impact-stream.wav`,
		frame: Math.round(S[5] + c6.start + 6),
		durationInFrames: 68,
		volume: 0.2,
	});

	// "STREAMING". Scene6.tsx:45 — TextNF start={cue.atText("streaming")}. This
	// is the same beat as the spinning DVD appearing (Scene6.tsx:49-66, `range`
	// from `dvd - 14`), so it is one cue, and it takes the technological marker
	// rather than a second impact.
	cues.push({
		src: `${NF_SFX}marker-tech.wav`,
		frame: Math.round(S[5] + c6.atText("streaming")),
		durationInFrames: 16,
		volume: 0.14,
	});

	// The photo swap to the streaming disc. Scene6.tsx:68-83 — the Netflix disc's
	// `range` opens at `swap = cue.atText("Naquele ano")` (Scene6.tsx:22).
	cues.push({
		src: `${NF_SFX}whoosh.wav`,
		frame: Math.round(S[5] + c6.atText("Naquele ano")),
		durationInFrames: 26,
		volume: 0.13,
	});

	// "US$ 1 BILHÃO". Scene6.tsx:87 — TextNF start={bil},
	// `bil = cue.atText("um bilhão")` (Scene6.tsx:23).
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[5] + c6.atText("um bilhão")),
		durationInFrames: 40,
		volume: 0.18,
	});

	/* ---- Scene 7 (originals, 2013) — SCENE_STARTS_NF[6] ---- */

	const c7 = cueForNF(6)("07-originais");

	// ALUGAR, the first state of the word under the photos. Scene7.tsx:137 —
	// WordMorph step at `cue.start + 8`.
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[6] + c7.start + 8),
		durationInFrames: 14,
		volume: 0.11,
	});

	// TRANSMITIR. Scene7.tsx:138 — step at `cue.atText("terminado de mudar")`.
	cues.push({
		src: `${NF_SFX}marker-tech.wav`,
		frame: Math.round(S[6] + c7.atText("terminado de mudar")),
		durationInFrames: 16,
		volume: 0.14,
	});

	// "2013". Scene7.tsx:128 — TextNF start={year + 4},
	// `year = cue.atText("Em dois mil")` (Scene7.tsx:81).
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[6] + c7.atText("Em dois mil") + 4),
		durationInFrames: 40,
		volume: 0.16,
	});

	// The photo swap to the second set photo. Scene7.tsx:107-126 — the photo's
	// `range` opens at `swap = cue.start + 112` (Scene7.tsx:82).
	cues.push({
		src: `${NF_SFX}whoosh.wav`,
		frame: Math.round(S[6] + c7.start + 112),
		durationInFrames: 26,
		volume: 0.13,
	});

	// PRODUZIR. Scene7.tsx:139 — step at `cue.atText("produzir")`.
	cues.push({
		src: `${NF_SFX}marker-tech.wav`,
		frame: Math.round(S[6] + c7.atText("produzir")),
		durationInFrames: 16,
		volume: 0.14,
	});

	// "ORIGINAIS" in the accent colour. Scene7.tsx:131 — TextNF start={orig},
	// `orig = cue.atText("próprias")` (Scene7.tsx:83).
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[6] + c7.atText("próprias")),
		durationInFrames: 14,
		volume: 0.12,
	});

	/* ---- Scene 8 (the world) — SCENE_STARTS_NF[7] ---- */

	const c8 = cueForNF(7)("08-mundo");

	// The one point in Los Gatos arriving on the map. Scene8.tsx:54 — `settle`
	// ramps the point in over the scene's first 24 frames (Scene8.tsx:96-107).
	// A deep sonar, not a bell.
	cues.push({
		src: `${NF_SFX}sonar.wav`,
		frame: S[7] + 2,
		durationInFrames: 74,
		volume: 0.13,
	});

	// "2016". Scene8.tsx:112 — TextNF start={y2016},
	// `y2016 = cue.atText("janeiro")` (Scene8.tsx:35).
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[7] + c8.atText("janeiro")),
		durationInFrames: 40,
		volume: 0.16,
	});

	// The scale of the world: the camera pulls back and the light spreads in
	// waves out of Los Gatos. Scene8.tsx:38 — `pull` ramps from
	// `wave = cue.atText("cento e trinta") - 6` (Scene8.tsx:33); the three wave
	// circles run from there (Scene8.tsx:63-79) and the countries light up to
	// the last of them (Scene8.tsx:80-94). One swell covers the expansion — the
	// dots themselves get no ticks, they are dozens and would be noise.
	cues.push({
		src: `${NF_SFX}swell.wav`,
		frame: Math.round(S[7] + c8.atText("cento e trinta") - 6),
		durationInFrames: 86,
		volume: 0.17,
	});

	// "+130 PAÍSES". Scene8.tsx:115 — TextNF start={wave + 8}.
	cues.push({
		src: `${NF_SFX}marker.wav`,
		frame: Math.round(S[7] + c8.atText("cento e trinta") - 6 + 8),
		durationInFrames: 14,
		volume: 0.12,
	});

	// "94 MILHÕES". Scene8.tsx:118 — TextNF start={subs},
	// `subs = cue.atText("noventa e quatro")` (Scene8.tsx:34).
	cues.push({
		src: `${NF_SFX}impact-soft.wav`,
		frame: Math.round(S[7] + c8.atText("noventa e quatro")),
		durationInFrames: 40,
		volume: 0.19,
	});

	/* ---- Scene 9 (the recap) — SCENE_STARTS_NF[8] ---- */

	const c9 = cueForNF(8)("09-transformacao");

	// The five stages of the timeline landing one at a time, each with its dot
	// and its thumbnail wipe. Scene9.tsx:89-93 — the `stages` array: DVD at
	// `cue.start + 4`, ASSINATURA at `cue.atText("Primeiro")`, STREAMING at
	// `cue.atText("Depois")`, ORIGINAIS at `cue.atText("E então")`, MUNDO at
	// `cue.atText("histórias") - 4`. The one technology word takes the
	// technological marker; the rest are plain ticks.
	for (const stage of [
		{at: c9.start + 4, tech: false, volume: 0.11},
		{at: c9.atText("Primeiro"), tech: false, volume: 0.11},
		{at: c9.atText("Depois"), tech: true, volume: 0.14},
		{at: c9.atText("E então"), tech: false, volume: 0.12},
		{at: c9.atText("histórias") - 4, tech: false, volume: 0.12},
	]) {
		cues.push({
			src: stage.tech ? `${NF_SFX}marker-tech.wav` : `${NF_SFX}marker.wav`,
			frame: Math.round(S[8] + stage.at),
			durationInFrames: stage.tech ? 16 : 14,
			volume: stage.volume,
		});
	}

	/* ---- Scene 10 (the close) — SCENE_STARTS_NF[9] ---- */

	// The wordmark surfacing alone after the photo has sunk to black. The only
	// effect in the close and the last sound of the film. Scene10.tsx:24-26 and
	// :50-59 — `markOp` ramps from `sink + 12` to `sink + 36`.
	cues.push({
		src: `${NF_SFX}logomark.wav`,
		frame: MARK_AT_NF,
		durationInFrames: 56,
		volume: 0.12,
	});

	return cues.sort((a, b) => a.frame - b.frame);
};

export const AUDIO_NF = {
	music: {
		enabled: true,
		src: "audio/netflix/score.wav",
		peakVolume: 0.5,
		/** The bed comes up under the hook and every spoken line ducks it. */
		fadeInFrames: 90,
		/** Scene 5 — the question, on its first word. From here the bed widens. */
		riseStart: S[4] + c5Curve.start,
		/** Scene 8 — the pull-back, where the world expands. The peak. */
		peakStart: Math.round(S[7] + c8Curve.atText("cento e trinta") - 6),
		/** Scene 9 — the recap: the bed starts letting go. */
		easeStart: S[8],
		/** Scene 10 — the close. */
		finalStart: S[9],
		/** The wordmark surfacing; from here the bed leaves. */
		fadeOutStart: MARK_AT_NF + 16,
		totalFrames: END_NF,
	},
	sfx: {
		enabled: true,
		get cues(): SfxCue[] {
			return computeSfxCuesNF();
		},
	},
};
