import {NARRATION_MQ, wordMQ} from "./narration-mq";
import {SCENE_STARTS_MQ} from "./timeline-mq";

/**
 * Sound design for "MaquinaIA".
 *
 * Everything here is generated by `node tools/generate-audio.mjs maquina` —
 * no samples and no stock audio anywhere in this project.
 *
 * There is NO bed: this piece has no music, by request. So every sound in the
 * film is one of the thirteen effects in public/audio/mq/, and each one exists
 * because something specific happens on screen at that frame — a card landing,
 * a station lighting up, the render bar completing, the stamp of "DO ZERO",
 * the rocket climbing. A scene change with no event in it gets nothing (the
 * cut into the phone in scene 5 is the only thing there, and it gets a single
 * quarter-second screen-on).
 *
 * No frame below is typed in: each cue is read from the words of
 * src/narration-mq.json through the same `wordMQ` the scenes use via
 * `cueLocalMQ` (see src/utils/timeline-mq.ts), so re-measuring the voice
 * re-times the whole sound design for free. The few cues that are purely
 * visual are the scene's own offset from that word, and the comment says which
 * line of which scene file produces it.
 *
 * Reference (30 fps, 1882 frames): scene starts 0 / 84 / 243 / 448 / 910 /
 * 1005 / 1300 — all derived, never typed in.
 *
 * Mixing: the voice commands. Every effect sits between 0.10 and 0.22, the
 * loudest ones (the cut, the two "EU QUERO") at 0.19-0.20, and nothing here
 * ever pauses or shortens a spoken line — a cue that disappears under the
 * words is doing its job.
 *
 * `cues` is a getter rather than a plain array, the same pattern as audio-nf.ts
 * and audio-cc.ts: the cues are computed at render time, after every module
 * has finished initialising, and they always read the current narration.
 */
const MQ_SFX = "audio/mq/";

type SfxCue = {src: string; frame: number; durationInFrames: number; volume: number};

/** Width of each effect in frames at 30 fps — printed by the generator, rounded up. */
const LEN = {
	impactCut: 36, // 1,20 s
	powerUp: 60, // 2,00 s
	tick: 8, // 0,26 s
	stationOn: 15, // 0,50 s
	ideaChime: 33, // 1,10 s
	lampSlide: 36, // 1,20 s
	renderDone: 36, // 1,20 s
	screenOn: 14, // 0,45 s
	gridOpen: 45, // 1,50 s
	impactCta: 54, // 1,80 s
	riserLikes: 33, // 1,10 s
	stamp: 24, // 0,80 s
	rocket: 87, // 2,90 s
} as const;

/** Absolute frame where a spoken word begins: the line's own frame plus the
 *  offset of the word inside it, straight from narration-mq.json. */
const word = (id: string, re: RegExp): number => wordMQ(id, re);

const computeSfxCuesMQ = (): SfxCue[] => {
	if (!NARRATION_MQ.enabled) return [];

	const cues: SfxCue[] = [];

	/* ---- Scene 1 (hook) — starts at SCENE_STARTS_MQ[0] ---- */

	// The hard cut to "EU MONTEI UMA.". Scene1Gancho.tsx:14 — `at` is
	// cueLocalMQ(0, "02-montei", /^montei$/) = frame 61, and it is the same
	// frame the scrim starts rising (Scene1Gancho.tsx:22, `at - 6` ... `at + 5`).
	// The one big hit of the opening.
	cues.push({src: `${MQ_SFX}impact-cut.wav`, frame: word("02-montei", /^montei$/), durationInFrames: LEN.impactCut, volume: 0.2});

	/* ---- Scene 2 (the reveal) — starts at SCENE_STARTS_MQ[1] = 85 ---- */

	// The seven-node network closing around the miner. Scene2Revelacao.tsx:23 —
	// `time` is cueLocalMQ(1, "04-time", /^time$/) = frame 157; the nodes then
	// pop two frames apart (Scene2Revelacao.tsx:100) and the miner's card lands
	// with it. One cue for the whole assembly: the nodes are seven and would be
	// a machine gun as separate ticks.
	cues.push({src: `${MQ_SFX}power-up.wav`, frame: word("04-time", /^time$/), durationInFrames: LEN.powerUp, volume: 0.15});

	/* ---- Scene 3 (the list of seven) — starts at SCENE_STARTS_MQ[2] = 243 ---- */

	// One card per spoken name. Scene3Lista.tsx:25 — `at` per card, from the
	// CARDS array at Scene3Lista.tsx:8-16. A dry tick each, and the last one
	// (Render, the card that closes the list) a hair louder than the six.
	const CARDS: {word: RegExp; volume: number}[] = [
		{word: /^Diretor\.$/, volume: 0.1},
		{word: /^Motion\.$/, volume: 0.1},
		{word: /^Revisor\.$/, volume: 0.1},
		{word: /^Narração\.$/, volume: 0.1},
		{word: /^Som\.$/, volume: 0.1},
		{word: /^Imagem$/, volume: 0.1},
		{word: /^Render\.$/, volume: 0.13},
	];
	for (const card of CARDS) {
		cues.push({src: `${MQ_SFX}tick.wav`, frame: word("05-lista", card.word), durationInFrames: LEN.tick, volume: card.volume});
	}

	/* ---- Scene 4 (the assembly line) — starts at SCENE_STARTS_MQ[3] = 386 ---- */

	// The idea lamp popping in. Scene4Sistema.tsx:32 — `idea` is
	// cueLocalMQ(3, "06-ideia", /^ideia\.$/) = frame 412, the same frame
	// `lampPop` (Scene4Sistema.tsx:35) springs from. The one piece of glass in
	// the film.
	const idea = word("06-ideia", /^ideia\.$/);
	cues.push({src: `${MQ_SFX}idea-chime.wav`, frame: idea, durationInFrames: LEN.ideaChime, volume: 0.15});

	// The lamp running down the belt to the first station. Scene4Sistema.tsx:36
	// — `lampRun` starts at `idea + 52` and takes 36 frames. Quiet: it goes by
	// under "A partir daí, cada agente entra em ação".
	cues.push({src: `${MQ_SFX}lamp-slide.wav`, frame: idea + 52, durationInFrames: LEN.lampSlide, volume: 0.1});

	// A station lighting up, one per role word. Scene4Sistema.tsx:53 — `active`
	// follows cueLocalMQ(3, "07-papeis", s.word) over the STATIONS array
	// (Scene4Sistema.tsx:15-23). Seven cues, ~1,5 s apart.
	const STATIONS: {word: RegExp; volume: number}[] = [
		{word: /^Diretor$/, volume: 0.13},
		{word: /^Motion$/, volume: 0.13},
		{word: /^Narração$/, volume: 0.13},
		{word: /^Som$/, volume: 0.13},
		{word: /^Imagem$/, volume: 0.13},
		{word: /^Revisor$/, volume: 0.13},
		{word: /^Render$/, volume: 0.14},
	];
	for (const station of STATIONS) {
		cues.push({src: `${MQ_SFX}station-on.wav`, frame: word("07-papeis", station.word), durationInFrames: LEN.stationOn, volume: station.volume});
	}

	// The render bar completing, and the phone appearing four frames later.
	// Scene4Sistema.tsx — `BAR_CUE` is the "Render" word above and
	// `BAR_LEN` is 26, so the bar fills at +26 and `phonePop` springs at +30.
	// One cue for the beat, not two.
	const barDone = word("07-papeis", /^Render$/) + 26;
	cues.push({src: `${MQ_SFX}render-done.wav`, frame: barDone, durationInFrames: LEN.renderDone, volume: 0.16});

	/* ---- Scene 5 (the video itself) — starts at SCENE_STARTS_MQ[4] = 850 ---- */

	// The phone screen coming on with this very film inside it.
	// Scene5VideoPronto.tsx:17 — `screenIn` ramps over the scene's first five
	// frames. The smallest sound of the piece, on the scene's own start.
	cues.push({src: `${MQ_SFX}screen-on.wav`, frame: SCENE_STARTS_MQ[4], durationInFrames: LEN.screenOn, volume: 0.1});

	/* ---- Scene 6 (the scale) — starts at SCENE_STARTS_MQ[5] = 945 ---- */

	// The creator turning into a grid of machines. Scene6Escala.tsx — the card
	// shrinks from `criar` (word("09-escala", /^Criar$/)) and the eight cells
	// pop from `criar + 14`, four frames apart. The eight pops are
	// inside grid-open.wav at exactly that stagger: one cue, not eight.
	cues.push({src: `${MQ_SFX}grid-open.wav`, frame: word("09-escala", /^Criar$/) + 14, durationInFrames: LEN.gridOpen, volume: 0.13});

	// The four platforms, one per spoken word. Scene6Escala.tsx:128 — the CHIPS
	// array at Scene6Escala.tsx:27-32, same tick as the seven cards.
	const CHIPS: RegExp[] = [/^TikTok,$/, /^YouTube,$/, /^publicidade,$/, /^afiliados$/];
	for (const chip of CHIPS) {
		cues.push({src: `${MQ_SFX}tick.wav`, frame: word("10-formas", chip), durationInFrames: LEN.tick, volume: 0.11});
	}

	/* ---- Scene 7 (the call to action) — starts at SCENE_STARTS_MQ[6] = 1264 ---- */

	// "EU QUERO" the first time. Scene7CTA.tsx:127 — the `Impact` at
	// cueLocalMQ(6, "11-quer", /^quero$/) = frame 1343. The button of the film.
	cues.push({src: `${MQ_SFX}impact-cta.wav`, frame: word("11-quer", /^quero$/), durationInFrames: LEN.impactCta, volume: 0.2});

	// The like counter running to 100 MIL. Scene7CTA.tsx:39 — `fill` runs from
	// `CEM` (cueLocalMQ(6, "12-teste", /^cem$/) = 1439) to `FILL_END`
	// (Scene7CTA.tsx:16, the end of "likes," plus 18) = 1467, which is exactly
	// the 33 frames this file is.
	cues.push({src: `${MQ_SFX}riser-likes.wav`, frame: word("12-teste", /^cem$/), durationInFrames: LEN.riserLikes, volume: 0.16});

	// "DO ZERO" stamped on. Scene7CTA.tsx:126 — the `Impact` with `stamp` at
	// cueLocalMQ(6, "13-zero", /^zero\.$/) = frame 1512.
	cues.push({src: `${MQ_SFX}stamp.wav`, frame: word("13-zero", /^zero\.$/), durationInFrames: LEN.stamp, volume: 0.16});

	// The second "EU QUERO", with the ring expanding out of it.
	// Scene7CTA.tsx:110-127 — `QUERO2` is cueLocalMQ(6, "15-cta2", /^quero,$/)
	// = 1667 and the ring springs from there. The same chord as the first, a
	// touch lower: it is a reminder, not a new idea.
	cues.push({src: `${MQ_SFX}impact-cta.wav`, frame: word("15-cta2", /^quero,$/), durationInFrames: LEN.impactCta, volume: 0.19});

	// The rocket climbing after the last line. Scene7CTA.tsx:51 — `rise` runs
	// from `VAMOS` (cueLocalMQ(6, "16-fim", /^Vamos$/) = 1767) for 72 frames.
	// The last sound of the film.
	cues.push({src: `${MQ_SFX}rocket.wav`, frame: word("16-fim", /^Vamos$/), durationInFrames: LEN.rocket, volume: 0.17});

	return cues.sort((a, b) => a.frame - b.frame);
};

export const AUDIO_MQ = {
	/** No bed: this piece has no music (it was not asked for). */
	music: {enabled: false},
	sfx: {
		enabled: true,
		get cues(): SfxCue[] {
			return computeSfxCuesMQ();
		},
	},
};
