/** Toda imagem real da peça "Coca-Cola" (esta lista vira os créditos via tools/creditos.mjs). */
export type ImageCC = {
	/** Path under public/, for staticFile(). */
	path: string;
	width: number;
	height: number;
	author: string;
	license: string;
	source: string;
	/** What the picture actually SHOWS — a modern photo is never stamped with an old date. */
	epoca: string;
	/** Scenes (1-based) where it appears. Empty means kept on disk but unused. */
	scenes: number[];
	note?: string;
};

/**
 * Gerado por tools/imagens-cc.mjs a partir de public/images/cocacola/fontes.json.
 * Todo o material vem do Wikimedia Commons / Openverse com licença declarada.
 */
export const IMG_CC = {
	_01_COCACOLAGLASSBOTTLE_JPG: {
		path: "images/cocacola/01-abertura/01-cocacolaglassbottle-jpg.jpg",
		width: 1556,
		height: 3846,
		author: "Biso",
		license: "CC BY-SA 3.0",
		source: "https://commons.wikimedia.org/wiki/File:CocaColaGlassBottle.jpg",
		epoca: "atual (fotografia de 2008)",
		scenes: [1] as number[],
		note: "Garrafa contour de vidro cheia de Coca-Cola com gelo, fundo branco liso, vertical. Fundo claro: recortar sobre o preto ou usar como inset. É a imagem de abertura pedida — a garrafa é reconhecível de imediato.",
	},
	_02_COSTONS_STORE_SODA_FOUNTAIN_1909_3200492358_JPG: {
		path: "images/cocacola/01-abertura/02-costons-store-soda-fountain-1909-3200492358-jpg.jpg",
		width: 1920,
		height: 1542,
		author: "Frank R. Snyder (Miami University Libraries)",
		license: "Public domain",
		source: "https://commons.wikimedia.org/wiki/File:Costons_store_soda_fountain_1909_(3200492358).jpg",
		epoca: "1909",
		scenes: [3] as number[],
		note: "Interior de loja com soda fountain em 1909; o letreiro pintado 'Coca-Cola' aparece sobre o balcão. Preto e branco de época, com pessoas.",
	},
	_01_MARBLE_DRAUGHT_STAND_HARPER_S_ENGRAVING_PNG: {
		path: "images/cocacola/02-pemberton/01-marble-draught-stand-harper-s-engraving-png.png",
		width: 1920,
		height: 1898,
		author: "Desconhecido (gravura de Harper's Weekly)",
		license: "Public domain",
		source: "https://commons.wikimedia.org/wiki/File:Marble_Draught_Stand_(Harper%27s_engraving).png",
		epoca: "1872",
		scenes: [2] as number[],
		note: "Gravura de 1872 de um balcão de bebidas gasosas ('draught stand') — o móvel de mármore onde a Coca-Cola era servida como remédio de farmácia.",
	},
	_02_ATLANTA_STREET_MAP_1888_JPG: {
		path: "images/cocacola/02-pemberton/02-atlanta-street-map-1888-jpg.jpg",
		width: 1920,
		height: 2352,
		author: "George F. Cram",
		license: "Public domain",
		source: "https://commons.wikimedia.org/wiki/File:Atlanta_Street_Map,_1888.jpg",
		epoca: "1888",
		scenes: [2] as number[],
		note: "Mapa das ruas de Atlanta em 1888 (Cram's Standard American Atlas) — a cidade e o ano em que a Coca-Cola já existia e crescia.",
	},
	_03_CHAS_B_PETER_PHARMACY_NEW_ORLEANS_POSTCARD_JPG: {
		path: "images/cocacola/02-pemberton/03-chas-b-peter-pharmacy-new-orleans-postcard-jpg.jpg",
		width: 1086,
		height: 704,
		author: "R. R. Patton (editor do postal)",
		license: "Public domain",
		source: "https://commons.wikimedia.org/wiki/File:Chas_B_Peter_Pharmacy_New_Orleans_postcard.jpg",
		epoca: "1908",
		scenes: [] as number[],
		note: "Postal de 1908 do interior de uma farmácia com soda fountain e cartazes de Coca-Cola nas paredes. Menor resolução do conjunto — usar em tamanho médio, não em tela cheia.",
	},
	_04_PEMBERTON_S_FRENCH_WINE_COCA_ADVERTISEMENT_JPG: {
		path: "images/cocacola/02-pemberton/04-pemberton-s-french-wine-coca-advertisement-jpg.jpg",
		width: 1287,
		height: 1860,
		author: "J. S. Pemberton & Co.",
		license: "Public domain (PD-US-expired)",
		source: "https://commons.wikimedia.org/wiki/File:Pemberton%27s_French_Wine_Coca_advertisement.jpg",
		epoca: "c. 1885",
		scenes: [] as number[],
		note: "Página de anúncio do French Wine Coca, o tônico de Pemberton imediatamente anterior à Coca-Cola. É o produto dele que aparece aqui, não a Coca-Cola.",
	},
	_01_COCA_COLA_COME_DRINK_A_GLASS_JPG: {
		path: "images/cocacola/03-anuncio/01-coca-cola-come-drink-a-glass-jpg.jpg",
		width: 1920,
		height: 2726,
		author: "The Coca-Cola Company (digitalizado pelo Internet Archive)",
		license: "Public domain",
		source: "https://commons.wikimedia.org/wiki/File:Coca-Cola,_come-drink_a_glass.jpg",
		epoca: "1915",
		scenes: [] as number[],
		note: "Anúncio de página inteira de revista de 1915, com a garrafa e o copo desenhados. Tipografia e arte de época legíveis.",
	},
	_02_DRINK_COCA_COLA_5_CENTS_LCCN2004671509_JPG: {
		path: "images/cocacola/03-anuncio/02-drink-coca-cola-5-cents-lccn2004671509-jpg.jpg",
		width: 1920,
		height: 2626,
		author: "The Coca-Cola Company (litografia); Library of Congress",
		license: "Public domain (PD-old-70, anterior a 1923)",
		source: "https://commons.wikimedia.org/wiki/File:Drink_Coca-Cola_5_cents_LCCN2004671509.jpg",
		epoca: "1890s",
		scenes: [3] as number[],
		note: "Cromolitografia 'Drink Coca-Cola 5¢' — a modelo de chapéu e vestido de época com o copo na mão, o cartaz mais reconhecível da virada do século.",
	},
	_03_19TH_CENTURY_COCA_COLA_COUPON_JPG: {
		path: "images/cocacola/03-anuncio/03-19th-century-coca-cola-coupon-jpg.jpg",
		width: 1295,
		height: 646,
		author: "The Coca-Cola Company",
		license: "Public domain (PD-US)",
		source: "https://commons.wikimedia.org/wiki/File:19th_century_Coca-Cola_coupon.jpg",
		epoca: "c. 1888",
		scenes: [3] as number[],
		note: "O cupom de copo grátis — 'This card entitles you to one glass of FREE Coca-Cola'. Horizontal e estreito: usar como faixa/inset, não em tela cheia.",
	},
	_01_ASA_G_C_JPG: {
		path: "images/cocacola/04-candler/01-asa-g-c-jpg.jpg",
		width: 1920,
		height: 2604,
		author: "Desconhecido",
		license: "Public domain (PD-US)",
		source: "https://commons.wikimedia.org/wiki/File:Asa_G._C..jpg",
		epoca: "desconhecida",
		scenes: [4] as number[],
		note: "Retrato de estúdio de Asa Candler, o farmacêutico que comprou a Coca-Cola de Pemberton. ATENÇÃO: o Commons não declara a data — NÃO carimbar ano nesta imagem.",
	},
	_02_ASA_G_CANDLER_COCA_COLA_KING_OF_ATLANTA_GEORGIA_LCCN201689: {
		path: "images/cocacola/04-candler/02-asa-g-candler-coca-cola-king-of-atlanta-georgia-lccn201689.jpg",
		width: 1920,
		height: 1488,
		author: "Harris & Ewing",
		license: "Public domain",
		source: "https://commons.wikimedia.org/wiki/File:Asa_G._Candler,_Coca_Cola_king_of_Atlanta,_Georgia_LCCN2016892491.tif",
		epoca: "1923",
		scenes: [] as number[],
		note: "Negativo de vidro de 1923 (Harris & Ewing, Library of Congress): Candler de chapéu-coco à porta do escritório. A moldura do negativo faz parte do quadro — recortar se preciso.",
	},
	_03_VINTAGE_COCA_COLA_DELIVERY_TRUCK_AT_THE_BIEDENHARN_MUSEUM_: {
		path: "images/cocacola/04-candler/03-vintage-coca-cola-delivery-truck-at-the-biedenharn-museum-.jpg",
		width: 1920,
		height: 1318,
		author: "Carol M. Highsmith",
		license: "Public domain (PD-Highsmith)",
		source: "https://commons.wikimedia.org/wiki/File:Vintage_Coca-Cola_delivery_truck_at_the_Biedenharn_Museum_%26_Gardens_in_Monroe_Louisiana.tif",
		epoca: "caminhão dos anos 1920 (fotografia de 2020)",
		scenes: [] as number[],
		note: "Caminhão de entrega da Coca-Cola restaurado, com engradados de garrafas, no museu Biedenharn (Monroe, Louisiana). O VEÍCULO é dos anos 1920; a FOTOGRAFIA é de 2020. Saiu da cena 4: foto moderna não pode dividir quadro com o ano 1892.",
	},
	_04_ADVERTISEMENT_FOR_NEW_COCA_COLA_BOTTLING_PLANT_1115_1117_C: {
		path: "images/cocacola/04-candler/04-advertisement-for-new-coca-cola-bottling-plant-1115-1117-c.jpg",
		width: 1920,
		height: 2270,
		author: "St. Louis Post-Dispatch (anúncio da Coca-Cola Bottling Co., St. Louis)",
		license: "Public domain (PD-Art, PD-US-expired)",
		source: "https://commons.wikimedia.org/wiki/File:Advertisement_for_new_Coca-Cola_Bottling_Plant,_1115-1117_Clark_Ave.,_St._Louis,_Missouri,_September_30,_1917.jpg",
		epoca: "1917",
		scenes: [] as number[],
		note: "Página inteira do St. Louis Post-Dispatch de 30/09/1917 (acervo do Missouri History Museum), com o anúncio da nova fábrica engarrafadora: manchete 'What Are You Drinking?', a garrafa contour desenhada e o endereço '1115-1117 Clark Ave., St. Louis'. Legível e nítido. É um documento de jornal de época — a cena pode isolar só a metade direita (o anúncio) e dispensar as colunas de notícias da esquerda.",
	},
	_05_COCA_COLA_BOTTLING_WORKS_PHOTOGRAPH_DPLA_8CEF949405119AB28: {
		path: "images/cocacola/04-candler/05-coca-cola-bottling-works-photograph-dpla-8cef949405119ab28.jpg",
		width: 1920,
		height: 1504,
		author: "Desconhecido (Columbus Metropolitan Library / Digital Public Library of America)",
		license: "Public domain (PD-US)",
		source: "https://commons.wikimedia.org/wiki/File:Coca_Cola_Bottling_Works_photograph_-_DPLA_-_8cef949405119ab28430973c01749516.jpg",
		epoca: "1926",
		scenes: [4] as number[],
		note: "Fotografia de época (1926) do prédio da Coca-Cola Bottling Works, impressa com a legenda 'COCA-COLA BOTTLING WORKS — Largest in Ohio and Among Finest in the Country'. Prédio de dois andares visto de esquina, na retícula de impressão da publicação de origem (meio-tom visível). Fundo claro. É a única foto REAL de época de uma planta engarrafadora encontrada no Commons.",
	},
	_01_COCA_COLA_LOGO_SVG: {
		path: "images/cocacola/05-identidade/01-coca-cola-logo-svg.png",
		width: 1920,
		height: 604,
		author: "The Coca-Cola Company",
		license: "Public domain (PD-textlogo)",
		source: "https://commons.wikimedia.org/wiki/File:Coca-Cola_logo.svg",
		epoca: "1887",
		scenes: [5, 7] as number[],
		note: "O logotipo em letra spenceriana (desenhado por Frank Mason Robinson em 1887), renderizado do SVG a 1920 px. Fundo transparente. Marca registrada: uso nominativo/descritivo no documentário.",
	},
	_02_COKE_BOTTLE_PATENT_PNG: {
		path: "images/cocacola/05-identidade/02-coke-bottle-patent-png.png",
		width: 1588,
		height: 2612,
		author: "Alexander Samuelson (inventor); US Patent Office",
		license: "Public domain",
		source: "https://commons.wikimedia.org/wiki/File:Coke_bottle_patent.png",
		epoca: "1915",
		scenes: [5] as number[],
		note: "A patente de desenho da garrafa contour (US D48.160), requerida em 18/08/1915 e concedida em 16/11/1915. Documento técnico: fundo claro, ótimo como inset.",
	},
	_03_VIEILLE_AFFICHE_COCA_ATLANTA_JPG: {
		path: "images/cocacola/05-identidade/03-vieille-affiche-coca-atlanta-jpg.jpg",
		width: 1920,
		height: 1440,
		author: "Rundvald",
		license: "Public domain (PD-self)",
		source: "https://commons.wikimedia.org/wiki/File:Vieille-affiche-Coca-Atlanta.JPG",
		epoca: "desconhecida (placa antiga preservada em Atlanta; fotografia de 2007)",
		scenes: [] as number[],
		note: "Placa pintada na parede — 'CARLOS SODA CO. / DRINK Coca-Cola / DELICIOUS AND REFRESHING' — preservada numa rua antiga de Atlanta. O Commons não declara a data da placa: NÃO carimbar ano.",
	},
	_04_LILLIAN_NORDICA_COCA_COLA_ADVERTISEMENT_IMG_4103_JPG: {
		path: "images/cocacola/05-identidade/04-lillian-nordica-coca-cola-advertisement-img-4103-jpg.jpg",
		width: 1920,
		height: 1280,
		author: "Billy Hathorn (fotografia); The Coca-Cola Company (anúncio)",
		license: "CC0",
		source: "https://commons.wikimedia.org/wiki/File:Lillian_Nordica_Coca-Cola_advertisement_IMG_4103.JPG",
		epoca: "1904 (fotografia de 2014)",
		scenes: [] as number[],
		note: "O anúncio de 1904 estrelado pela soprano Lillian Nordica, fotografado emoldurado no museu Biedenharn em 2014. A moldura e o reflexo do vidro aparecem na foto. Saiu da cena 5: o painel do museu ao fundo imprime 1904/1905/1906 e um cartaz moderno, misturando épocas.",
	},
	_01_1930S_COCA_COLA_NEON_SIGN_JPG: {
		path: "images/cocacola/06-escala/01-1930s-coca-cola-neon-sign-jpg.jpg",
		width: 1920,
		height: 1280,
		author: "Ben Franske (fotografia)",
		license: "CC BY-SA 4.0",
		source: "https://commons.wikimedia.org/wiki/File:1930s_Coca-Cola_Neon_Sign.jpg",
		epoca: "letreiro dos anos 1930 (fotografia de 2009)",
		scenes: [] as number[],
		note: "Letreiro de neon dos anos 1930, originalmente da Griffin Drug Store (Edina, Minnesota), aceso com as cores da marca. O LETREIRO é dos anos 1930; a FOTOGRAFIA é de 2009.",
	},
	_02_WORKING_FOR_COKE_6868754014_JPG: {
		path: "images/cocacola/06-escala/02-working-for-coke-6868754014-jpg.jpg",
		width: 1920,
		height: 1280,
		author: "Alex Proimos",
		license: "CC BY 2.0",
		source: "https://commons.wikimedia.org/wiki/File:Working_for_Coke_(6868754014).jpg",
		epoca: "2012",
		scenes: [6] as number[],
		note: "Descarga de engradados de Coca-Cola de um caminhão, no Peru (2012). Foto atual: a escala mundial da distribuição, não material histórico.",
	},
	_03_COCA_COLA_NEON_SIGN_AT_THE_CENTER_OF_DOWNTOWN_ATLANTA_AT_S: {
		path: "images/cocacola/06-escala/03-coca-cola-neon-sign-at-the-center-of-downtown-atlanta-at-s.jpg",
		width: 1920,
		height: 2880,
		author: "Marc Merlin",
		license: "CC BY-SA 4.0",
		source: "https://commons.wikimedia.org/wiki/File:Coca-Cola_neon_sign_at_the_center_of_downtown_Atlanta_at_Sunset.jpg",
		epoca: "atual (2019 ou depois)",
		scenes: [] as number[],
		note: "O letreiro de neon da Coca-Cola no centro de Atlanta ao pôr do sol, vertical. Foto atual; o letreiro existe desde os anos 1960 — não usar como imagem de época.",
	},
	_01_COCA_COLA_SIGN_OLYMPIA_BUILDING_ATLANTA_GA_46559099455_JPG: {
		path: "images/cocacola/07-final/01-coca-cola-sign-olympia-building-atlanta-ga-46559099455-jpg.jpg",
		width: 1920,
		height: 2560,
		author: "Warren LeMay",
		license: "CC0",
		source: "https://commons.wikimedia.org/wiki/File:Coca-Cola_Sign,_Olympia_Building,_Atlanta,_GA_(46559099455).jpg",
		epoca: "letreiro de 1960s (fotografia de 2019)",
		scenes: [7] as number[],
		note: "O letreiro da Coca-Cola sobre o Olympia Building, em Atlanta, à noite: vermelho e branco fortes sobre fundo escuro. Vertical, serve bem de fecho.",
	},
	_02_CROSSVILLESIGN_EDIT_PNG: {
		path: "images/cocacola/07-final/02-crossvillesign-edit-png.png",
		width: 1920,
		height: 2734,
		author: "Ben Shahn",
		license: "Public domain (PD-USGov-FSA)",
		source: "https://commons.wikimedia.org/wiki/File:Crossvillesign-edit.png",
		epoca: "1937",
		scenes: [7] as number[],
		note: "Fotografia de Ben Shahn para a Farm Security Administration em 1937, no Tennessee: um letreiro pintado de Coca-Cola na parede, com transeuntes. Documento real da Depressão, não publicidade da marca.",
	},
} satisfies Record<string, ImageCC>;

export const ALL_IMAGES_CC: ImageCC[] = Object.values(IMG_CC);
