#!/usr/bin/env node
// Generates biblioteca/componentes/icone/icones.ts + icones.json from lucide-static SVGs.
// Usage: node tools/gera-icones.mjs /tmp/opencode/lucide/package/icons
// Skips (with a warning) any icon name that does not exist in lucide-static.
import fs from "node:fs";
import path from "node:path";

const SRC = process.argv[2];
const ALVO = path.resolve(new URL("../biblioteca/componentes/icone", import.meta.url).pathname);
if (!SRC || !fs.existsSync(SRC)) {
	console.error("uso: node tools/gera-icones.mjs <pasta-dos-svgs-do-lucide-static>");
	process.exit(2);
}

// Curated catalog: categoria → ícones (names as in lucide-static).
const LISTA = {
	energia: ["zap", "flame", "sun", "battery-charging", "sparkles", "rocket", "wind"],
	crescimento: ["trending-up", "arrow-up-right", "sprout", "leaf", "bar-chart-3", "mountain", "layers"],
	dinheiro: ["coins", "dollar-sign", "wallet", "credit-card", "briefcase", "trending-down", "piggy-bank", "banknote", "receipt", "percent"],
	coracao: ["heart", "heart-handshake", "smile", "thumbs-up", "users", "gift", "party-popper"],
	mente: ["brain", "lightbulb", "book-open", "graduation-cap", "pencil", "pen-tool", "palette", "search", "message-circle", "mic", "languages", "book"],
	tempo: ["clock", "hourglass", "calendar", "timer", "watch", "history", "alarm-clock"],
	vitoria: ["trophy", "target", "crown", "gem", "medal", "award", "star", "check-circle", "flag", "shield-check"],
	natureza: ["tree-pine", "flower-2", "waves", "cloud-sun", "cloud-rain", "umbrella", "snowflake", "moon", "sunrise", "sunset"],
	tech: ["laptop", "smartphone", "cpu", "circuit-board", "database", "cloud", "wifi", "bluetooth", "battery", "code", "monitor", "tablet", "terminal", "server", "shield", "lock", "key", "settings", "wrench", "download", "upload"],
	casa: ["home", "building-2", "factory", "store", "coffee", "bed"],
	saude: ["activity", "stethoscope", "pill", "apple", "dumbbell", "thermometer", "shield-plus"],
	comunicacao: ["megaphone", "share-2", "send", "link", "mail", "phone", "video", "camera", "image", "map-pin", "globe", "bell"],
	objetos: ["box", "package", "truck", "shopping-cart", "shopping-bag", "cart"],
	extra: ["play", "pause", "music", "headphones", "film", "tv", "cog", "alert-triangle", "info", "check", "x", "plus", "minus", "refresh-cw", "repeat", "trash-2", "folder", "file-text", "clipboard", "printer", "save", "eye", "eye-off", "volume-2", "phone-call", "car", "bike", "train-front", "ship", "anchor", "map", "compass"],
};

const ATTRS = /(\w[\w-]*)="([^"]*)"/g;

function el(tag, attrsTexto) {
	const a = {};
	let m;
	while ((m = ATTRS.exec(attrsTexto))) a[m[1]] = m[2];
	return {t: tag, a};
}

function leIcone(nome) {
	const arq = path.join(SRC, `${nome}.svg`);
	if (!fs.existsSync(arq)) return null;
	const svg = fs.readFileSync(arq, "utf8");
	const els = [];
	const re = /<(path|circle|rect|line|polyline|polygon)\b([^>]*)\/?>/g;
	let m;
	while ((m = re.exec(svg))) els.push(el(m[1], m[2]));
	return els.length ? els : null;
}

const icones = {}; // nome -> elementos
const categorias = {}; // nome -> categoria
const faltantes = [];
for (const [cat, nomes] of Object.entries(LISTA)) {
	for (const nome of nomes) {
		const els = leIcone(nome);
		if (!els) { faltantes.push(nome); continue; }
		icones[nome] = els;
		categorias[nome] = cat;
	}
}

fs.mkdirSync(ALVO, {recursive: true});
const ts = `/** Generated by tools/gera-icones.mjs from lucide-static (ISC). Do not edit by hand. */
export type IconeEl = {t: string; a: Record<string, string>};

export const ICONES: Record<string, IconeEl[]> = ${JSON.stringify(icones)} as const;
`;
fs.writeFileSync(path.join(ALVO, "icones.ts"), ts);
fs.writeFileSync(path.join(ALVO, "icones.json"), JSON.stringify({categorias, total: Object.keys(icones).length}, null, 1) + "\n");
console.log(`icones: ${Object.keys(icones).length} gerados, ${faltantes.length} nomes não existem no lucide: ${faltantes.join(", ")}`);
